"""Generate a per-config iverilog testbench that traces per-cycle activity.

The testbench instantiates `wau_top` with the same parameters as the existing
fixtures, feeds it stimulus loaded via `$readmemh`, and dumps one block of
structured `$fwrite` lines per simulation cycle. The Python frontend parses
that text trace and never re-implements the WAU's cycle semantics itself.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable


TB_TEMPLATE = r"""`timescale 1ns/1ps
`include "wau_defs.vh"

// Auto-generated by wau-pipelines-viewer. Do not hand-edit.
module tb_wau_viewer;
    parameter integer DATA_WIDTH    = `WAU_DATA_WIDTH;
    parameter integer FLOW_ID_WIDTH = `WAU_FLOW_ID_WIDTH;
    parameter integer OPCODE_WIDTH  = `WAU_OPCODE_WIDTH;
    parameter integer GRID_X        = `WAU_GRID_X;
    parameter integer GRID_Y        = `WAU_GRID_Y;
    parameter integer CORE_COUNT    = `WAU_CORE_COUNT;
    parameter integer STIM_COUNT    = %(stim_count)d;
    parameter integer MAX_CYCLES    = %(max_cycles)d;

    // Data-plane payload layout — must mirror wau_top's DATA_* localparams so we
    // can decode each per-core data-plane delivery (the "data packet arriving at
    // a core" event used to animate data movement in the viewer).
    localparam integer TB_CORE_ID_WIDTH      = 8;
    // Highway geometry, straight from the emitted defs so the trace follows
    // whatever topology was generated.
    localparam integer TB_LINE_COUNT         = `WAU_HIGHWAY_LINE_COUNT;
    localparam integer TB_LINE_SIZE          = `WAU_HIGHWAY_LINE_SIZE;
    // Mirrors wau_top's COORDINATOR_CORE_INDEX.
    localparam integer TB_COORDINATOR_CORE   = 0;
    localparam integer TB_DATA_FLOW_ID_LSB   = 0;
    localparam integer TB_DATA_STAGE_LSB     = TB_DATA_FLOW_ID_LSB + FLOW_ID_WIDTH;
    localparam integer TB_DATA_VALUE_LSB     = TB_DATA_STAGE_LSB + 8;
    localparam integer TB_DATA_SRC_CORE_LSB  = TB_DATA_VALUE_LSB + DATA_WIDTH;
    // Fast-path fields, appended in exactly the order wau_top's own
    // DATA_*_LSB chain appends them (see verilog_emit.py's _render_top) --
    // this trace decodes the real, generated payload, so drift here would
    // silently desync the two the same way AGENTS.md's "Viewer route
    // drifting from the emitted router" pitfall warns about for routing.
    localparam integer TB_DATA_IS_FAST_PATH_LSB = TB_DATA_SRC_CORE_LSB + TB_CORE_ID_WIDTH;
    localparam integer TB_DATA_NEXT_STAGE_LSB   = TB_DATA_IS_FAST_PATH_LSB + 1;
    localparam integer TB_DATA_NEXT_OPCODE_LSB  = TB_DATA_NEXT_STAGE_LSB + 8;
    localparam integer TB_DATA_NEXT_USE_IMM_LSB = TB_DATA_NEXT_OPCODE_LSB + OPCODE_WIDTH;
    localparam integer TB_DATA_NEXT_IMM_LSB     = TB_DATA_NEXT_USE_IMM_LSB + 1;
    localparam integer TB_DATA_B_REG_LSB        = TB_DATA_NEXT_IMM_LSB + DATA_WIDTH;
    localparam integer TB_DATA_PAYLOAD_WIDTH    = TB_DATA_B_REG_LSB + DATA_WIDTH;

    reg clk;
    reg rst_n;

    reg host_in_valid;
    wire host_in_ready;
    reg [FLOW_ID_WIDTH-1:0] host_in_flow_id;
    reg signed [DATA_WIDTH-1:0] host_in_a;
    reg signed [DATA_WIDTH-1:0] host_in_b;

    wire host_out_valid;
    reg host_out_ready;
    wire [FLOW_ID_WIDTH-1:0] host_out_flow_id;
    wire signed [DATA_WIDTH-1:0] host_out_value;

    reg enable_auto_adapt;

    wire [31:0] obs_total_hop_count;
    wire [31:0] obs_total_stall_count;
    wire [31:0] obs_total_forward_count;
    wire [31:0] obs_total_local_delivered_count;
    wire [31:0] obs_total_cache_hit_count;
    wire [31:0] obs_total_cache_lookup_count;
    wire [31:0] obs_total_contract_grant_count;
    wire [31:0] obs_total_contract_hold_cycles;
    wire [31:0] obs_total_contract_defer_count;

    wau_top dut (
        .clk(clk),
        .rst_n(rst_n),
        .host_in_valid(host_in_valid),
        .host_in_ready(host_in_ready),
        .host_in_flow_id(host_in_flow_id),
        .host_in_a(host_in_a),
        .host_in_b(host_in_b),
        .host_out_valid(host_out_valid),
        .host_out_ready(host_out_ready),
        .host_out_flow_id(host_out_flow_id),
        .host_out_value(host_out_value),
        .enable_auto_adapt(enable_auto_adapt),
        .obs_total_hop_count(obs_total_hop_count),
        .obs_total_stall_count(obs_total_stall_count),
        .obs_total_forward_count(obs_total_forward_count),
        .obs_total_local_delivered_count(obs_total_local_delivered_count),
        .obs_total_cache_hit_count(obs_total_cache_hit_count),
        .obs_total_cache_lookup_count(obs_total_cache_lookup_count),
        .obs_total_contract_grant_count(obs_total_contract_grant_count),
        .obs_total_contract_hold_cycles(obs_total_contract_hold_cycles),
        .obs_total_contract_defer_count(obs_total_contract_defer_count)
    );

    always #5 clk = ~clk;

    // Stimulus loaded via $readmemh: hex columns produced by the Python frontend.
    reg [FLOW_ID_WIDTH-1:0] stim_flow_id [0:STIM_COUNT-1];
    reg signed [DATA_WIDTH-1:0] stim_a    [0:STIM_COUNT-1];
    reg signed [DATA_WIDTH-1:0] stim_b    [0:STIM_COUNT-1];

    integer trace_f;
    integer cycle_counter;
    integer stim_idx;
    integer core_i;
    integer hwy_line;
    integer deliv_line;
    integer outputs_seen;

    initial begin
        if (STIM_COUNT > 0) begin
            $readmemh("stim_flow.hex", stim_flow_id);
            $readmemh("stim_a.hex",    stim_a);
            $readmemh("stim_b.hex",    stim_b);
        end
        trace_f = $fopen("trace.log", "w");
        if (trace_f == 0) begin
            $display("FATAL: cannot open trace.log");
            $finish;
        end
        $fwrite(trace_f, "# wau-pipelines-viewer trace v1\n");
        $fwrite(trace_f, "META grid_x=%%0d grid_y=%%0d core_count=%%0d stim_count=%%0d line_count=%%0d line_size=%%0d\n",
            GRID_X, GRID_Y, CORE_COUNT, STIM_COUNT, TB_LINE_COUNT, TB_LINE_SIZE);
    end

    // Per-cycle trace dump. We snapshot just before negedge so dispatch / result
    // handshakes registered on the previous posedge are visible to the host
    // before the next cycle starts.
    always @(negedge clk) begin
        if (rst_n) begin
            $fwrite(trace_f, "@CYCLE %%0d\n", cycle_counter);
            $fwrite(trace_f, "HOST_IN v=%%0d r=%%0d flow=%%0d a=%%0d b=%%0d\n",
                host_in_valid, host_in_ready, host_in_flow_id, host_in_a, host_in_b);
            $fwrite(trace_f, "HOST_OUT v=%%0d r=%%0d flow=%%0d val=%%0d\n",
                host_out_valid, host_out_ready, host_out_flow_id, host_out_value);
            for (core_i = 0; core_i < CORE_COUNT; core_i = core_i + 1) begin
                $fwrite(trace_f, "CORE %%0d busy=%%0d cache_hit=%%0d",
                    core_i,
                    dut.core_busy[core_i],
                    dut.core_cache_hit[core_i]);
                if (dut.core_dispatch_valid[core_i] && dut.core_dispatch_ready[core_i]) begin
                    $fwrite(trace_f, " disp=1 disp_op=%%0d disp_a=%%0d disp_b=%%0d disp_imm=%%0d disp_use_imm=%%0d disp_stage=%%0d disp_flow=%%0d",
                        dut.core_dispatch_opcode[(core_i*OPCODE_WIDTH) +: OPCODE_WIDTH],
                        $signed(dut.core_dispatch_a[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        $signed(dut.core_dispatch_b[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        $signed(dut.core_dispatch_immediate_b[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        dut.core_dispatch_use_immediate[core_i],
                        dut.core_dispatch_stage_id[(core_i*8) +: 8],
                        dut.core_dispatch_flow_id[(core_i*FLOW_ID_WIDTH) +: FLOW_ID_WIDTH]);
                end else if (dut.core_self_dispatch_valid[core_i] && dut.core_self_dispatch_ready[core_i]) begin
                    // Fast-path self-dispatch (compiler.station_program): this
                    // core just started an op handed to it directly by another
                    // core's station, bypassing wau_coordinator entirely, so it
                    // never touches core_dispatch_valid/ready above. Without this
                    // branch the Gantt strip's dispatch/result FIFO (built from
                    // `disp`/`res` events) never sees a start event for it: the
                    // eventual `res=1` either gets silently dropped (no pending
                    // entry to close) or wrongly closes an unrelated older
                    // pending entry, stretching its bar out to the fast-path
                    // op's completion cycle. Mutually exclusive with the branch
                    // above by construction (wau_core_station's `in_ready` is
                    // forced low whenever `self_valid` is asserted).
                    $fwrite(trace_f, " disp=1 disp_op=%%0d disp_a=%%0d disp_b=%%0d disp_imm=%%0d disp_use_imm=%%0d disp_stage=%%0d disp_flow=%%0d disp_fastpath=1",
                        dut.core_self_dispatch_opcode[(core_i*OPCODE_WIDTH) +: OPCODE_WIDTH],
                        $signed(dut.core_self_dispatch_a[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        $signed(dut.core_self_dispatch_b_reg[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        $signed(dut.core_self_dispatch_immediate_b[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        dut.core_self_dispatch_use_immediate[core_i],
                        dut.core_self_dispatch_stage_id[(core_i*8) +: 8],
                        dut.core_self_dispatch_flow_id[(core_i*FLOW_ID_WIDTH) +: FLOW_ID_WIDTH]);
                end
                if (dut.core_result_valid[core_i] && dut.core_result_ready[core_i]) begin
                    $fwrite(trace_f, " res=1 res_val=%%0d res_stage=%%0d res_flow=%%0d",
                        $signed(dut.core_result_value[(core_i*DATA_WIDTH) +: DATA_WIDTH]),
                        dut.core_result_stage_id[(core_i*8) +: 8],
                        dut.core_result_flow_id[(core_i*FLOW_ID_WIDTH) +: FLOW_ID_WIDTH]);
                end
                // Data-plane delivery to this core: a result packet that has
                // travelled the data mesh and is consumed here this cycle. This
                // exposes the per-link/per-core data movement the viewer animates
                // (src core -> this core), previously not present in the trace.
                if (dut.data_local_out_valid[core_i] && dut.data_local_out_ready[core_i]) begin
                    $fwrite(trace_f, " ddeliv=1 ddeliv_src=%%0d ddeliv_val=%%0d ddeliv_flow=%%0d ddeliv_stage=%%0d ddeliv_fastpath=%%0d",
                        dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_SRC_CORE_LSB +: TB_CORE_ID_WIDTH],
                        $signed(dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_VALUE_LSB +: DATA_WIDTH]),
                        dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_FLOW_ID_LSB +: FLOW_ID_WIDTH],
                        dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_STAGE_LSB +: 8],
                        dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_IS_FAST_PATH_LSB +: 1]);
                    if (dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_IS_FAST_PATH_LSB +: 1]) begin
                        $fwrite(trace_f, " ddeliv_next_stage=%%0d ddeliv_next_op=%%0d",
                            dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_NEXT_STAGE_LSB +: 8],
                            dut.data_local_out_payload[(core_i*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_NEXT_OPCODE_LSB +: OPCODE_WIDTH]);
                    end
                end else if (core_i == TB_COORDINATOR_CORE) begin
                    // With one highway per line a result leaves the fabric at
                    // its line's hub, not at a core's local port. The result
                    // arbiter grants a single line per cycle, so at most one
                    // hub handshakes here; attribute it to the coordinator,
                    // which is where the value actually lands.
                    //
                    // ddeliv_fastpath=1 here specifically means a fast-path-
                    // tagged packet whose destination was on a *different*
                    // highway line: there is no hub-to-hub bridge, so it was
                    // absorbed by the coordinator instead of ever reaching
                    // its intended core (safe -- see wau_coordinator's
                    // relaxed result matching -- but not a speedup for that
                    // hop). ddeliv_next_stage/_next_op are meaningless here
                    // (the coordinator ignores them), so unlike the per-core
                    // branch above they are not emitted.
                    for (deliv_line = 0; deliv_line < TB_LINE_COUNT; deliv_line = deliv_line + 1) begin
                        if (dut.data_hub_out_valid[deliv_line] && dut.data_hub_out_ready[deliv_line]) begin
                            $fwrite(trace_f, " ddeliv=1 ddeliv_line=%%0d ddeliv_src=%%0d ddeliv_val=%%0d ddeliv_flow=%%0d ddeliv_stage=%%0d ddeliv_fastpath=%%0d",
                                deliv_line,
                                dut.data_hub_out_payload[(deliv_line*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_SRC_CORE_LSB +: TB_CORE_ID_WIDTH],
                                $signed(dut.data_hub_out_payload[(deliv_line*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_VALUE_LSB +: DATA_WIDTH]),
                                dut.data_hub_out_payload[(deliv_line*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_FLOW_ID_LSB +: FLOW_ID_WIDTH],
                                dut.data_hub_out_payload[(deliv_line*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_STAGE_LSB +: 8],
                                dut.data_hub_out_payload[(deliv_line*TB_DATA_PAYLOAD_WIDTH) + TB_DATA_IS_FAST_PATH_LSB +: 1]);
                        end
                    end
                end
                // Highway contract bus, per core: `hwy_req` is the core asking
                // for its highway, `hwy_call` is that ask landing on its own
                // offered slot (the moment a core *calls* the highway), and
                // `hwy_hold` marks the core that currently owns it. Each core
                // is arbitrated by ITS OWN line's bus, so the grant is compared
                // against that line's state and a line-local core id.
                hwy_line = core_i / TB_LINE_SIZE;
                $fwrite(trace_f, " hwy_req=%%0d hwy_call=%%0d hwy_hold=%%0d",
                    dut.data_contract_req[core_i],
                    dut.data_contract_call[core_i],
                    dut.data_contract_grant_valid[hwy_line]
                        && (dut.data_contract_grant_core[(hwy_line*TB_CORE_ID_WIDTH) +: TB_CORE_ID_WIDTH]
                            == (core_i %% TB_LINE_SIZE)));
                $fwrite(trace_f, " cache_h_count=%%0d cache_l_count=%%0d\n",
                    dut.core_cache_hit_count[(core_i*32) +: 32],
                    dut.core_cache_lookup_count[(core_i*32) +: 32]);
            end
            // Per-highway contract state: one record per LINE, since each line
            // arbitrates independently. `slot`/`gcore` are line-local ids; the
            // grant/hold/defer totals are fabric-wide and repeated on each
            // record so a reader never has to join across lines.
            for (hwy_line = 0; hwy_line < TB_LINE_COUNT; hwy_line = hwy_line + 1) begin
                $fwrite(trace_f, "HWY line=%%0d slot=%%0d grant=%%0d gcore=%%0d gmode=%%0d grem=%%0d grants=%%0d hold=%%0d defer=%%0d\n",
                    hwy_line,
                    dut.data_contract_slot[(hwy_line*TB_CORE_ID_WIDTH) +: TB_CORE_ID_WIDTH],
                    dut.data_contract_grant_valid[hwy_line],
                    dut.data_contract_grant_core[(hwy_line*TB_CORE_ID_WIDTH) +: TB_CORE_ID_WIDTH],
                    dut.data_contract_grant_mode[(hwy_line*2) +: 2],
                    dut.data_contract_grant_remaining[(hwy_line*16) +: 16],
                    obs_total_contract_grant_count,
                    obs_total_contract_hold_cycles,
                    obs_total_contract_defer_count);
            end
            $fwrite(trace_f, "OBS hops=%%0d stalls=%%0d forwards=%%0d deliv=%%0d cache_h=%%0d cache_l=%%0d\n",
                obs_total_hop_count, obs_total_stall_count, obs_total_forward_count,
                obs_total_local_delivered_count, obs_total_cache_hit_count, obs_total_cache_lookup_count);
        end
    end

    // Stimulus driver: walks `stim_*.hex` and feeds the host input port using
    // ready/valid backpressure, then drains the output stream for a fixed grace
    // period so the trace captures the final result.
    initial begin
        clk = 1'b0;
        rst_n = 1'b0;
        host_in_valid = 1'b0;
        host_in_flow_id = {FLOW_ID_WIDTH{1'b0}};
        host_in_a = {DATA_WIDTH{1'b0}};
        host_in_b = {DATA_WIDTH{1'b0}};
        host_out_ready = 1'b1;
        enable_auto_adapt = 1'b1;
        cycle_counter = 0;
        outputs_seen = 0;

        repeat (4) @(posedge clk);
        rst_n = 1'b1;

        for (stim_idx = 0; stim_idx < STIM_COUNT; stim_idx = stim_idx + 1) begin
            @(negedge clk);
            host_in_flow_id = stim_flow_id[stim_idx];
            host_in_a       = stim_a[stim_idx];
            host_in_b       = stim_b[stim_idx];
            host_in_valid   = 1'b1;
            while (!host_in_ready) @(posedge clk);
            @(negedge clk);
            host_in_valid = 1'b0;
        end

        while (cycle_counter < MAX_CYCLES && outputs_seen < STIM_COUNT) begin
            @(posedge clk);
        end

        $fwrite(trace_f, "@END total_cycles=%%0d outputs_seen=%%0d\n",
            cycle_counter, outputs_seen);
        $fclose(trace_f);
        $finish;
    end

    always @(posedge clk) begin
        if (!rst_n) begin
            cycle_counter <= 0;
            outputs_seen <= 0;
        end else begin
            cycle_counter <= cycle_counter + 1;
            if (host_out_valid && host_out_ready) outputs_seen <= outputs_seen + 1;
        end
    end

endmodule
"""


def render_testbench(stim_count: int, max_cycles: int) -> str:
    return TB_TEMPLATE % {"stim_count": max(stim_count, 1), "max_cycles": max_cycles}


def _twos(v: int, width: int) -> str:
    if v < 0:
        v = (1 << width) + v
    return f"{v & ((1 << width) - 1):0{width // 4}x}"


def write_stimulus_hex(
    directory: Path,
    flow_ids: Iterable[int],
    a_values: Iterable[int],
    b_values: Iterable[int],
) -> None:
    """Write the three column files consumed by `$readmemh` in the testbench."""
    directory.mkdir(parents=True, exist_ok=True)
    flows = list(flow_ids)
    a_vals = list(a_values)
    b_vals = list(b_values)
    n = len(flows)
    if not (len(a_vals) == n and len(b_vals) == n):
        raise ValueError("stimulus columns must have the same length")
    if n == 0:
        flows = [0]
        a_vals = [0]
        b_vals = [0]
    (directory / "stim_flow.hex").write_text(
        "\n".join(_twos(v, 12) for v in flows) + "\n"
    )
    (directory / "stim_a.hex").write_text(
        "\n".join(_twos(v, 32) for v in a_vals) + "\n"
    )
    (directory / "stim_b.hex").write_text(
        "\n".join(_twos(v, 32) for v in b_vals) + "\n"
    )
